#
# JBoss, Home of Professional Open Source.
# Copyright 2023 Red Hat, Inc., and individual contributors
# as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Adjustments related to running in OCP environment
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../components/core
  - ../../../components/cache
  - ../../../components/tekton
  - ../../../components/service
patchesStrategicMerge:
  - patches/sbomer-database-connection.yaml
  - patches/service.yaml
  - patches/sa.yaml
resources:
  - resources/route.yaml
patches:
  - target:
      kind: Task
    patch: |-
      - op: replace
        path: /spec/steps/0/imagePullPolicy
        value: Always
  - target:
      kind: StatefulSet
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: sbomer
    patch: |-
      - op: add
        path: /spec/template/spec/initContainers/-
        value:
          image: quay.io/rh-newcastle/pnc-vault-secrets:1.0.0
          name: get-vault-secrets
          resources:
            limits:
              cpu: 0.2
              memory: 200Mi
            requests:
              cpu: 0.2
              memory: 200Mi
          command:
            - /bin/bash
          args:
            - -c
            - cd /mnt/secrets;
              pnc-vault-secrets dump $(SBOMER_SECRET_NAME)-$(APP_ENV);
          env:
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault-connection-info
                  key: vault-address
            - name: VAULT_APP_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-connection-info
                  key: vault-app-role-id
            - name: VAULT_APP_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-connection-info
                  key: vault-app-secret-id
            - name: SBOMER_SECRET_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['sbomer-secret']
            - name: APP_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['environment']
          volumeMounts:
            - name: secrets-workdir
              mountPath: /mnt/secrets
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: secrets-workdir
          mountPath: /mnt/secrets
          readOnly: true
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: sbomer-certs-volume
          mountPath: /etc/pki/ca-trust/source/anchors
          subPath: ca-trust/source/anchors
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: sbomer-certs-volume
          mountPath: /etc/pki/ca-trust/extracted
          subPath: ca-trust/extracted
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: volume-thread-dump
          mountPath: /mnt/thread-dump
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: volume-thread-heap-dump-script
          mountPath: /mnt/thread-heap-dump-script
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: secrets-workdir
          emptyDir:
            medium: Memory
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: sbomer-certs-volume
          persistentVolumeClaim:
            claimName: sbomer-ca-trust-certificate
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: volume-thread-dump
          persistentVolumeClaim:
            claimName: pnc-threaddump
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: volume-thread-heap-dump-script
          configMap:
            defaultMode: 360
            name: pnc-thread-heap-dump
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE
          value: "1"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: QUARKUS_DATASOURCE_JDBC_MIN_SIZE
          value: "0"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: QUARKUS_DATASOURCE_JDBC_MAX_SIZE
          value: "20"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SBOMER_SECRET_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['sbomer-secret']
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['environment']
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: CONSUMER_TOPIC
          value: "$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/consumer.topic)"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PRODUCER_TOPIC
          value: "$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/producer.topic)"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: UMB_BROKER_URL
          value: "$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/qpid-jms.url)"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: QUARKUS_OIDC_AUTH_SERVER_URL
          value: "$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/auth-server-url.txt)"


