#
# JBoss, Home of Professional Open Source.
# Copyright 2023 Red Hat, Inc., and individual contributors
# as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

mp:
  messaging:
    incoming:
      builds:
        port: ${UMB_BROKER_PORT}
        address: ${sbomer.features.umb.consumer.topic}
        host: "${UMB_BROKER_HOST}"
    outgoing:
      finished:
        port: ${UMB_BROKER_PORT}
        address: "topic://${sbomer.features.umb.producer.topic}"
        host: "${UMB_BROKER_HOST}"

sbomer:
  api-url: "https://${SBOMER_ROUTE_HOST}/api/v1alpha2/"

  purl-qualifiers-allow-list:
    - repository_url

  controller:
    generation-request:
      # This path is (in the service deployment) the mount
      # point of the PVC shared between TaskRuns and controller
      sbom-dir: "/data"
      cleanup: true

  features:
    umb:
      enabled: true
      consumer:
        enabled: true
        topic: "${CONSUMER_TOPIC}"
      producer:
        enabled: true
        topic: "${PRODUCER_TOPIC}"

quarkus:
  log:
    console:
      # Enable JSON logging to console in production
      json:
        ~: true

  oidc:
    enabled: true
    connection-delay: 30S
    connection-retry-count: 10
    client-id: pnc-sbomer
    tls:
      verification: none

  # https://quarkus.io/guides/opentelemetry
  otel:
    enabled: true
