#
# JBoss, Home of Professional Open Source.
# Copyright 2023 Red Hat, Inc., and individual contributors
# as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##
# PRODUCTION OVERLAY
#
# This overlay deploys the full service using images from our CI
# on a production OpenShift environment.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../targets/ocp
patchesStrategicMerge:
  - patches/tekton/cm.yaml
patches:
  # - target:
  #     kind: Deployment
  #     name: sbomer-cache
  #   patch: |-
  #     - op: add
  #       path: /spec/template/spec/containers/0/env/-
  #       value:
  #         name: PNC_SERVICE_HOST
  #         value: "orch.psi.redhat.com"
  #     - op: add
  #       path: /spec/template/spec/containers/0/env/-
  #       value:
  #         name: INDY_REPOSITORY_HOST
  #         value: "indy.psi.redhat.com"
  - target:
      kind: Deployment
      name: sbomer
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sbomer-secrets
              key: pnc-sbomer.password
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JAVA_TOOL_OPTIONS
          value: "-Djavax.net.ssl.keyStore=/mnt/secrets-sbomer/pnc-sbomer.pkcs12 -Djavax.net.ssl.keyStorePassword=$(KEYSTORE_PASSWORD) -Djavax.net.ssl.keyStoreType=PKCS12 -XX:MaxRAMPercentage=70.0 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap-dump.hprof -XX:OnOutOfMemoryError='python /mnt/thread-heap-dump-script/thread_heap_dump_email.py'"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SBOMER_PRODUCT_MAPPING_ENV
          value: "production"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SBOMER_ROUTE_HOST
          value: "sbomer.apps.ocp-c1.prod.psi.redhat.com"
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 1000m
            memory: 2000Mi
          limits:
            cpu: 1000m
            memory: 2000Mi
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: QUARKUS_OIDC_AUTH_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: sbomer-secrets
              key: auth-server-url.txt

  - target:
      kind: Route
    patch: |-
      - op: replace
        path: /spec/host
        value: "sbomer.apps.ocp-c1.prod.psi.redhat.com"


# List of images used in production
# TODO: Currently happily using :latest tag but this will be changed in the future
images:
  - name: sbomer-generator
    newName: quay.io/rh-newcastle/sbomer-generator:latest
  - name: sbomer-service
    newName: quay.io/rh-newcastle/sbomer-service:latest
  - name: sbomer-cache
    newName: quay.io/rh-newcastle/sbomer-cache:latest
