#
# JBoss, Home of Professional Open Source.
# Copyright 2023 Red Hat, Inc., and individual contributors
# as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##
# STAGING OVERLAY
#
# This overlay deploys the full service using images from our CI
# on a staging OpenShift environment.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../targets/ocp
patchesStrategicMerge:
  - patches/tekton/cm.yaml
  - patches/sbomer-cache-deployment.yaml
patches:
  - target:
      kind: Deployment
      name: sbomer
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/environment
        value: stage
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: KEYSTORE_PASSWORD
          value: "$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/nonprod-pnc-sbomer.password)"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JAVA_TOOL_OPTIONS
          value: "-Djavax.net.ssl.keyStore=/mnt/secrets/nonprod-pnc-sbomer.pkcs12 -Djavax.net.ssl.keyStorePassword=$(KEYSTORE_PASSWORD) -Djavax.net.ssl.keyStoreType=PKCS12 -XX:MaxRAMPercentage=70.0 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap-dump.hprof -XX:OnOutOfMemoryError='python /mnt/thread-heap-dump-script/thread_heap_dump_email.py'"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SBOMER_PRODUCT_MAPPING_ENV
          value: "staging"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SBOMER_ROUTE_HOST
          value: "sbomer-stage.apps.ocp-c1.prod.psi.redhat.com"
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 1000m
            memory: 2000Mi
          limits:
            cpu: 1000m
            memory: 2000Mi

  - target:
      kind: Route
    patch: |-
      - op: replace
        path: /spec/host
        value: "sbomer-stage.apps.ocp-c1.prod.psi.redhat.com"

# List of images used in staging
# TODO: Currently happily using :latest tag but this will be changed in the future
images:
  - name: sbomer-generator
    newName: quay.io/rh-newcastle-stage/sbomer-generator:latest
  - name: sbomer-service
    newName: quay.io/rh-newcastle-stage/sbomer-service:latest
  - name: sbomer-cache
    newName: quay.io/rh-newcastle-stage/sbomer-cache:latest
